spring.application.name=fulfillment-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/petstore

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
