spring.application.name=core
server.port=8080

spring.mongodb.uri=mongodb://localhost:27017/petstore

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

cors.allowed-origins=http://localhost:4200
